---
deployment:
  tasks:
    - export DEPLOYPATH=/home/hkdcfgyd/iqmediation
    - /bin/cp -R assets $DEPLOYPATH
    - /bin/cp -R docs $DEPLOYPATH
    - /bin/cp -R examples $DEPLOYPATH
    - /bin/cp *.* $DEPLOYPATH
    